### ISSUE TITLE
Creating catkin work space

### ISSUE THREAD

**Issue by max-nussbaum** [PTScientists/MANIansible#12]
### Issue
On running the ansible script I received the following Error:

TASK [ros : Create catkin workspace] 
fatal: [172.16.10.121]: FAILED! => {
    "changed": true, 
    "cmd": [
        "/bin/zsh", 
        "-c", 
        "source /opt/ros/kinetic/setup.zsh && mkdir -p /home/ubuntu/catkin_ws/src\n&& cd /home/ubuntu/catkin_ws && catkin_make"
    ], 
    "delta": "0:00:00.006420", 
    "end": "2019-04-03 10:01:23.287756", 
    "invocation": {
        "module_args": {
            "_raw_params": "/bin/zsh -c \"source /opt/ros/kinetic/setup.zsh && mkdir -p /home/ubuntu/catkin_ws/src\n&& cd /home/ubuntu/catkin_ws && catkin_make\"", 
            "_uses_shell": false, 
            "argv": null, 
            "chdir": null, 
            "creates": "/home/ubuntu/catkin_ws", 
            "executable": null, 
            "removes": null, 
            "stdin": null, 
            "warn": true
        }
    }, 
    "msg": "non-zero return code", 
    "rc": 1, 
    "start": "2019-04-03 10:01:23.281336", 
    "stderr": "zsh:2: parse error near `&&'", 
    "stderr_lines": [
        "zsh:2: parse error near `&&'"
    ], 
    "stdout": "", 
    "stdout_lines": []
}
	to retry, use: --limit @/home/ubuntu/ROS/MANIansible/provision.retry

PLAY RECAP *****************************************************************************************************************************************************************************************************
172.16.10.121              : ok=15   changed=13   unreachable=0    failed=1  

### Solution
I'm not quite sure what has changed, but for some the shell commands did not accept "&&" as an operator.
I therefore changed the roles/ros/tasks/main.yml to run the commands individually:

- name: Create catkin workspace
  command: >-
    /bin/zsh -c "source /opt/ros/kinetic/setup.zsh"
    /bin/zsh -c "mkdir -p /home/ubuntu/catkin_ws/src"
    /bin/zsh -c "cd /home/ubuntu/catkin_w"
    /bin/zsh -c "catkin_make"

**Comment by mawalu** [comment]
+1 on the find, I encourage the same error when running the playbook on a fresh install. Does the solution you propose create the catkin workspace correctly for you?

**Comment by mawalu** [comment]
Fixed in bfefe42e98b34e3e83737929dff6d052193ae366
